package com.example.data.repository

import com.example.BuildConfig
import com.example.data.remote.AiPromptDto
import com.example.data.remote.GeminiApi
import com.example.data.remote.GeminiContent
import com.example.data.remote.GeminiGenerationConfig
import com.example.data.remote.GeminiPart
import com.example.data.remote.GeminiRequest
import com.squareup.moshi.Moshi
import javax.inject.Inject
import javax.inject.Singleton

private const val GEMINI_MODEL = "gemini-2.5-flash"

@Singleton
class AiPromptRepositoryImpl @Inject constructor(
    private val geminiApi: GeminiApi,
    private val moshi: Moshi
) : AiPromptRepository {

    // NOTE: BuildConfig.GEMINI_API_KEY is generated by the Secrets Gradle
    // Plugin from the GEMINI_API_KEY entry in the project's .env file.
    // Get a free key at https://aistudio.google.com/apikey and put it in
    // .env as: GEMINI_API_KEY=your_key_here  (do NOT commit .env).
    private val apiKey: String
        get() = BuildConfig.GEMINI_API_KEY

    override fun hasApiKey(): Boolean = apiKey.isNotBlank()

    override suspend fun generateStructuredPrompt(metaPrompt: String): AiPromptDto {
        require(hasApiKey()) {
            "GEMINI_API_KEY is missing. Add it to your .env file (see .env.example)."
        }

        val request = GeminiRequest(
            contents = listOf(
                GeminiContent(parts = listOf(GeminiPart(text = metaPrompt)), role = "user")
            ),
            generationConfig = GeminiGenerationConfig(temperature = 0.4)
        )

        val response = geminiApi.generateContent(
            model = GEMINI_MODEL,
            apiKey = apiKey,
            request = request
        )

        val rawJson = response.candidates
            ?.firstOrNull()
            ?.content
            ?.parts
            ?.firstOrNull()
            ?.text
            ?: throw IllegalStateException("Gemini returned an empty response.")

        val adapter = moshi.adapter(AiPromptDto::class.java)
        return adapter.fromJson(rawJson)
            ?: throw IllegalStateException("Could not parse Gemini's JSON reply: $rawJson")
    }
}
